# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-24 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0004_auto_20180331_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cec_module',
            name='Technology',
            field=models.IntegerField(choices=[(0, '1-a-Si'), (1, '2-a-Si'), (2, '3-a-Si'), (3, 'CIGS'), (4, 'CIS'), (5, 'CdTe'), (6, 'HIT-Si'), (7, 'Mono-c-Si'), (8, 'Multi-c-Si'), (9, 'Thin Film'), (10, 'a-Si'), (11, 'a-Si/nc')]),
        ),
        migrations.AlterField(
            model_name='cec_module',
            name='Version',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, 'MM105'), (2, 'MM106'), (3, 'MM107'), (4, 'NRELv1')], default=0),
        ),
        migrations.AlterField(
            model_name='pvinverter',
            name='Idcmax',
            field=models.FloatField(verbose_name='Max DC current [A]'),
        ),
        migrations.AlterField(
            model_name='pvinverter',
            name='Mppt_high',
            field=models.FloatField(verbose_name='Higher bound of MPPT [W]'),
        ),
        migrations.AlterField(
            model_name='pvinverter',
            name='Mppt_low',
            field=models.FloatField(verbose_name='Lower bound of MPPT [W]'),
        ),
        migrations.AlterField(
            model_name='pvinverter',
            name='Paco',
            field=models.FloatField(verbose_name='Rated AC power [W]'),
        ),
        migrations.AlterField(
            model_name='pvinverter',
            name='Pdco',
            field=models.FloatField(verbose_name='DC power [W]'),
        ),
        migrations.AlterField(
            model_name='pvinverter',
            name='Pnt',
            field=models.FloatField(verbose_name='Nighttime consumption [W]'),
        ),
        migrations.AlterField(
            model_name='pvinverter',
            name='Pso',
            field=models.FloatField(verbose_name='Self consumption [W]'),
        ),
        migrations.AlterField(
            model_name='pvinverter',
            name='Vac',
            field=models.FloatField(verbose_name='AC Voltage [V]'),
        ),
        migrations.AlterField(
            model_name='pvinverter',
            name='Vdcmax',
            field=models.FloatField(verbose_name='Max DC voltage [V]'),
        ),
        migrations.AlterField(
            model_name='pvinverter',
            name='Vdco',
            field=models.FloatField(verbose_name='DC voltage [V]'),
        ),
        migrations.AlterField(
            model_name='pvmodule',
            name='A',
            field=models.FloatField(verbose_name='Natural Convection Coeff'),
        ),
        migrations.AlterField(
            model_name='pvmodule',
            name='Aimp',
            field=models.FloatField(verbose_name='Max Power Current Tempco'),
        ),
        migrations.AlterField(
            model_name='pvmodule',
            name='Aisc',
            field=models.FloatField(verbose_name='Short Circuit Current Tempco'),
        ),
        migrations.AlterField(
            model_name='pvmodule',
            name='B',
            field=models.FloatField(verbose_name='Forced Convection Coeff'),
        ),
        migrations.AlterField(
            model_name='pvmodule',
            name='Bvmpo',
            field=models.FloatField(verbose_name='Max Power Voltage Tempco'),
        ),
        migrations.AlterField(
            model_name='pvmodule',
            name='Bvoco',
            field=models.FloatField(verbose_name='Open Circuit Voltage Tempco'),
        ),
        migrations.AlterField(
            model_name='pvmodule',
            name='DTC',
            field=models.FloatField(verbose_name='Cell Temp Delta'),
        ),
        migrations.AlterField(
            model_name='pvmodule',
            name='FD',
            field=models.FloatField(verbose_name='Diffuse Fraction'),
        ),
        migrations.AlterField(
            model_name='pvmodule',
            name='Impo',
            field=models.FloatField(verbose_name='Max Power Current [A]'),
        ),
        migrations.AlterField(
            model_name='pvmodule',
            name='Isco',
            field=models.FloatField(verbose_name='Short Circuit Current [A]'),
        ),
        migrations.AlterField(
            model_name='pvmodule',
            name='Material',
            field=models.IntegerField(choices=[(1, '2-a-Si'), (2, '3-a-Si'), (3, 'CIS'), (4, 'CdTe'), (5, 'EFG mc-Si'), (6, 'GaAs'), (7, 'HIT-Si'), (8, 'Si-Film'), (9, 'a-Si / mono-Si'), (10, 'c-Si'), (11, 'mc-Si')]),
        ),
        migrations.AlterField(
            model_name='pvmodule',
            name='N',
            field=models.FloatField(verbose_name='Diode Ideality Factor'),
        ),
        migrations.AlterField(
            model_name='pvmodule',
            name='Vmpo',
            field=models.FloatField(verbose_name='Max Power Voltage [V]'),
        ),
        migrations.AlterField(
            model_name='pvmodule',
            name='Voco',
            field=models.FloatField(verbose_name='Open Circuit Voltage [V]'),
        ),
    ]
