# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 04:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parameters', '0006_auto_20181125_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='cec_module',
            name='Bifacial',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='cec_module',
            name='Length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cec_module',
            name='STC',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cec_module',
            name='Width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cec_module',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cec_module',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cec_module',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cec_module',
            name='modified_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pvinverter',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pvinverter',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pvinverter',
            name='revision',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='pvmodule',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pvmodule',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pvmodule',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pvmodule',
            name='modified_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cec_module',
            name='Technology',
            field=models.IntegerField(choices=[(0, ''), (1, '1-a-Si'), (2, '2-a-Si'), (3, '3-a-Si'), (4, 'CIGS'), (5, 'CIS'), (6, 'CdTe'), (7, 'HIT-Si'), (8, 'Mono-c-Si'), (9, 'Multi-c-Si'), (10, 'Thin Film'), (11, 'a-Si'), (12, 'a-Si/nc')]),
        ),
        migrations.AlterField(
            model_name='cec_module',
            name='Version',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, 'MM105'), (2, 'MM106'), (3, 'MM107'), (4, 'NRELv1'), (5, 'SAM 2018.9.27'), (6, 'SAM 2018.10.29')], default=0),
        ),
        migrations.AlterField(
            model_name='pvmodule',
            name='Material',
            field=models.IntegerField(choices=[(0, ''), (1, '2-a-Si'), (2, '3-a-Si'), (3, 'CIS'), (4, 'CdTe'), (5, 'EFG mc-Si'), (6, 'GaAs'), (7, 'HIT-Si'), (8, 'Si-Film'), (9, 'a-Si / mono-Si'), (10, 'c-Si'), (11, 'mc-Si')]),
        ),
        migrations.AlterUniqueTogether(
            name='cec_module',
            unique_together=set([('Name', 'Date', 'Version')]),
        ),
        migrations.AlterUniqueTogether(
            name='pvinverter',
            unique_together=set([('Name', 'revision')]),
        ),
    ]
