# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0007_auto_20181129_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cec_module',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pvinverter',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
