# Generated by Django 2.2.28 on 2025-03-23 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0008_auto_20181129_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvinverter',
            name='CEC_Date',
            field=models.DateField(default=datetime.datetime(1990, 1, 1, 0, 0), verbose_name='CEC Date [%b %e %Y]'),
        ),
        migrations.AddField(
            model_name='pvinverter',
            name='CEC_Type',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
