# Generated by Django 2.2.28 on 2025-04-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0009_auto_20250322_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvinverter',
            name='SAM_Version',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, '2018.11.11.r2'), (2, '2018.11.11.r3-r4'), (3, '2020.2.29_Release-r1.ssc.238'), (4, '2020.2.29.r2.ssc.240-r3.ssc.242'), (5, '2020.11.29.r0.ssc.250-2021.12.02.r0.ssc.267'), (6, '2021.12.02.r1.ssc.268'), (7, '2021.12.02.r2.ssc.274'), (8, '2022.11.21.r0.ssc.278-r3.ssc.280'), (9, '2023.12.17.r0.ssc.288-r2.ssc.292'), (10, '2024.12.12.r0.ssc.298')], default=1),
        ),
    ]
