# Generated by Django 4.2.20 on 2025-05-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0013_auto_20250410_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='cec_module',
            name='Manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
