# Generated by Django 4.2.20 on 2025-05-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0014_cec_module_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pvinverter',
            name='SAM_Version',
            field=models.IntegerField(blank=True, choices=[(0, ''), (1, '2018.11.11.r2'), (2, '2018.11.11.r3-r4'), (3, '2020.2.29.r2.ssc.240'), (4, '2020.11.29.r0.ssc.250'), (5, '2021.12.02.r1.ssc.268'), (6, '2021.12.02.r2.ssc.274'), (7, '2022.11.21.r0.ssc.278'), (8, '2023.12.17.r0.ssc.288'), (9, '2024.12.12.r0.ssc.298')], default=0),
        ),
    ]
